# Generated by Django 3.2.13 on 2022-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
